"""
generate_templates.py
=======================
Builds the 5 master .docx proposal templates (Honeywell, Dassault,
Common Vendor, Foreign Vendor, General Notice) using python-docx,
based on config/proposal_config.json + config/field_mapping.json.

Run:
    python scripts/generate_templates.py

Each template contains a title, a header table (Reference No. / Date /
Document Type / Customer-Vendor / Reference), a Cover Letter section,
and a Proposal Summary table listing every mapped field with its
{{placeholder}} token. services/docx_export_service.py fills these
tokens with AI-retrieved (or user-edited) values.
"""

import json
import os
import sys

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

CONFIG_DIR = os.path.join(PROJECT_ROOT, "config")
BRAND_COLOR = RGBColor(0x4F, 0x46, 0xE5)  # indigo, matches the dashboard's primary accent color


def load_json(filename):
    with open(os.path.join(CONFIG_DIR, filename), "r", encoding="utf-8") as f:
        return json.load(f)


def style_heading(paragraph, text, size=16, color=BRAND_COLOR, bold=True, align_center=True):
    run = paragraph.add_run(text)
    run.bold = bold
    run.font.size = Pt(size)
    run.font.color.rgb = color
    if align_center:
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return run


def add_two_col_table(document, rows, header=None):
    table = document.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"
    if header:
        hdr_cells = table.add_row().cells
        hdr_cells[0].text, hdr_cells[1].text = header
        for cell in hdr_cells:
            for p in cell.paragraphs:
                for r in p.runs:
                    r.bold = True
    for label, value in rows:
        row_cells = table.add_row().cells
        row_cells[0].text = str(label)
        row_cells[1].text = str(value)
    return table


def build_template(proposal_type_cfg, field_mapping_cfg):
    type_id = proposal_type_cfg["id"]
    display_name = proposal_type_cfg["display_name"]
    header_fields = proposal_type_cfg["header_fields"]
    cover_letter_text = proposal_type_cfg["cover_letter"]

    fields = field_mapping_cfg["proposal_types"][type_id]["fields"]
    field_by_name = {f["field_name"]: f["placeholder_token"] for f in fields}

    document = Document()

    title_p = document.add_paragraph()
    style_heading(title_p, f"{display_name.upper()} TECHNICAL & COMMERCIAL PROPOSAL", size=18)

    subtitle_p = document.add_paragraph()
    style_heading(subtitle_p, f"{display_name} - Master Template", size=12, bold=False)

    document.add_paragraph()

    header_rows = [
        ("Reference No.", field_by_name.get(header_fields["reference_no"], "{{reference_no}}")),
        ("Date", "{{generation_date}}"),
        ("Document Type", display_name),
        ("Customer/Vendor", field_by_name.get(header_fields["customer_vendor"], "{{customer_vendor}}")),
        ("Reference", field_by_name.get(header_fields["reference"], "{{reference}}")),
    ]
    add_two_col_table(document, header_rows, header=("Field", "Value"))

    document.add_paragraph()

    cl_heading = document.add_paragraph()
    style_heading(cl_heading, "Cover Letter", size=13, align_center=False)

    document.add_paragraph("Dear Sir/Madam,")
    document.add_paragraph(cover_letter_text)
    document.add_paragraph()
    document.add_paragraph("Yours faithfully,")
    document.add_paragraph("Authorised Signatory")
    document.add_paragraph(display_name)

    document.add_paragraph()

    summary_heading = document.add_paragraph()
    style_heading(summary_heading, "Proposal Summary", size=13, align_center=False)

    summary_rows = [(name, token) for name, token in field_by_name.items()]
    add_two_col_table(document, summary_rows, header=("Description", "Retrieved Value"))

    document.add_paragraph()
    footer_p = document.add_paragraph()
    footer_run = footer_p.add_run(
        "Generated by the AI Procurement Proposal Generation System (Ollama-powered, fully local). "
        "Fields marked NA could not be automatically retrieved and require manual completion."
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    return document


def main():
    proposal_config = load_json("proposal_config.json")
    field_mapping = load_json("field_mapping.json")

    for proposal_type_cfg in proposal_config["proposal_types"]:
        template_path = os.path.join(PROJECT_ROOT, proposal_type_cfg["template_path"])
        os.makedirs(os.path.dirname(template_path), exist_ok=True)
        document = build_template(proposal_type_cfg, field_mapping)
        document.save(template_path)
        print(f"Generated template: {template_path}")


if __name__ == "__main__":
    main()
